### ISSUE TITLE
Not all expressions work in swan

### ISSUE THREAD

**Issue by veaceslav** [swandroid/swan-sense-studio#8]
Hello,

while trying to port swan to watch I figured out that not all swan expressions work:

This one works:
self@movement:x{ANY,100}

This one does not work:
self@movement:x?delay=2000{ANY, 100} -> this one is outputted by toCrossDeviceString

Also, the long expression outputted by SWAN Monitor which also contain delay, they also work.

Do I miss something?

After a little bit of digging, I figured out that adding the delay parameter will make 

ExpressionFactory.parseExpression() not to output a ValueExpression anymore. It returns an Expression, but casting it to ValueExpression will be null.

Then we get the following exception:

Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String interdroid.swancore.swansong.Expression.toParseString()' on a null object reference
                                                                                  at interdroid.swancore.swanmain.ExpressionManager.registerExpression(ExpressionManager.java:405)
                                                                                  at interdroid.swancore.swanmain.ExpressionManager.registerExpression(ExpressionManager.java:346)
                                                                                  at interdroid.swancore.swanmain.ExpressionManager.registerValueExpression(ExpressionManager.java:277)
                                                                                  at com.example.accelerometerapp.MainActivity.registerSWANSensor(MainActivity.java:81)
                                                                                  at com.example.accelerometerapp.MainActivity.initialize(MainActivity.java:54)
                                                                                  at com.example.accelerometerapp.MainActivity.onCreate(MainActivity.java:36)

**Comment by roshanbharathdas** [comment]
Use Swanmonitor to generate correct expression

**Comment by veaceslav** [comment]
This one is relevant for @vlady88 . The toCrossDeviceString produce an incompatible swan expression.
